### ISSUE TITLE
Add support for string based mode

### ISSUE THREAD

**Issue by Toilal** [YakDriver/oschmod#28]
**Is your feature request related to a problem? Please describe.**

Most of the time, when using GNU Coreutils chmod, I use the following syntax

```
chmod +x script.sh,
chmod go-rwx readonly.txt
```

But python doesn't have this, sadly ...

**Describe the solution you'd like**

Let's fork and implement this, and open a pull request ! Would you accept this feature ?

From GNU coreutils chmod --help, it should support this expression

`[ugoa]*([-+=]([rwxXst]*|[ugo]))+|[-+=][0-7]+`

**Describe alternatives you've considered**

subprocess.run(["chmod", ...]) but it's not portable. 

**Additional context**

**Comment by Toilal** [comment]
But this could be another module too, let's say `strchmod`, so it could work with `oschmod` or default `os.chmod`.

```
import os
import stat

import strchmod

strchmod.install() # This could monkeypatch `os.chmod` and `oschmod` if available.

# os.chmod('myfile', stat.S_IRUSR | stat.S_IWUSR | stat.S_IXUSR)
os.chmod('myfile', 'u=rwx')
```

**Comment by Toilal** [comment]
I have released a standalone module: https://github.com/Toilal/python-chmod-monkey

**Comment by YakDriver** [comment]
@Toilal Thanks for raising this issue! I'd like to add string support but wasn't up for it originally. Perhaps we can merge the functionality.

**Comment by Toilal** [comment]
@YakDriver I think it's better if the modules are disctinct as they deserves two different goals. 

But I could add `oschmod` support into chmod-monkey for monkeypatch support (like what I have done for original os.chmod). (Check the README)

People can still use chmod-monkey with the non-monkeypatch way for now

```
import os

from chmod_monkey import to_mode
import oschmod

oschmod.set_mode('script.sh', to_mode('script.sh', 'ug+x'))
```

**Comment by Toilal** [comment]
You could also add an optional dependency to chmod-monkey in order to support string. It's up to you :)

**Comment by YakDriver** [comment]
@Toilal Thanks for your thoughts on this. I went a different way but you can now use symbolic representations with oschmod directly:

```python
import oschmod

oschmod.set_mode('script.sh', 'ug+x')
```
